spring:
  profiles:
    active: dev

  application:
    name: framework
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filters: stat,wall
      initial-size: 1
      min-idle: 1
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      stat-view-servlet:
        reset-enable: true
        url-pattern: /druid/*
        login-username: admin
        login-password: 123
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/static/
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    cache: false
    prefix: classpath:/templates/
    suffix: .html

framework:
  data:
    mybatis:
      mapper-locations: classpath:/mapper/**.xml
  security:
    shiro:
      enabled: false
      default-access-level: anonymous
    token:
      secret: LWCQDRM7A9ZU58VP13FONT0KSHJ6XYBE
      expire: 7d
