server:
  port: 8786
  servlet:
    context-path: /


spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10mb
      max-request-size: 50mb
  application:
    name: framework
  datasource:
    url: jdbc:mysql://10.33.1.34:3306/bxp?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  redis:
    host: 10.33.1.34
    port: 6379
    database: 0
    password: 123456
    timeout: 1s
  rabbitmq:
      host: 10.33.1.55
      port: 5672
      username: root
      password: 123456
logging:
  path: C:\log
  level:
    root: info
    tx: debug
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
bxp:
  BackpurseUrl: http://10.33.1.156:8787/bbs_purse
  imgurl: http://10.33.1.55:8070/imgs/upload
  imgurl1: http://10.33.1.55:8090/files/imgs
  Actionname: 核查过期
  Opinion:  系统提示-任务过期
  Memo: 任务核查-核查过期
  DataUrl: http://127.0.0.1:8787/bxp