server:
  port: 8197
  servlet:
    context-path: /

multipart:
  enabled: true
  max-file-size: 10mb
  max-request-size: 50mb
spring:
  application:
    name: framework
  datasource:
    url: jdbc:mysql://10.33.1.34:3306/bxp?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  redis:
    host: 10.33.1.34
    port: 6379
    database: 0
    password: 123456
    timeout: 1s
  rabbitmq:
      host: 10.33.1.64
      port: 5672
      username: root
      password: 123456
logging:
  path: C:\log
  level:
    root: info
    tx: debug
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql